version: '3.3'
services:
  mb_api_backend:
    container_name: mb_api_backend
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - '3001:3001'
    links:
      - mb_api_db
    working_dir: /home/mb_api
    networks:
      - backend
    build:
      context: ../.
      dockerfile: ./build/server.dockerfile

  mb_api_db:
    container_name: mb_api_db
    restart: always
    env_file:
      - .env
    build:
      context: ..
      dockerfile: ./build/db.dockerfile
      args:
        dbuser: ${POSTGRES_USER}
        dbname: ${POSTGRES_DB}
        dbpasswd: ${POSTGRES_PASSWORD}

    volumes:
      - ../scripts/init.sql:/home/mb_api/init.sql
      - database-data:/var/lib/postgresql/data/
    #        - ./db/pg_hba.conf:/etc/postgresql/12/main/pg_hba.conf
    #        - ./db/postgresql.conf:/etc/postgresql/12/main/postgresql.conf
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    networks:
      - backend

volumes:
  database-data:

networks:
  backend: