// Code generated by MockGen. DO NOT EDIT.
// Source: mb_api/internal/pkg/prodncats (interfaces: UseCase)

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	models "mb_api/internal/pkg/models"
	reflect "reflect"
)

// MockUseCase is a mock of UseCase interface
type MockUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUseCaseMockRecorder
}

// MockUseCaseMockRecorder is the mock recorder for MockUseCase
type MockUseCaseMockRecorder struct {
	mock *MockUseCase
}

// NewMockUseCase creates a new mock instance
func NewMockUseCase(ctrl *gomock.Controller) *MockUseCase {
	mock := &MockUseCase{ctrl: ctrl}
	mock.recorder = &MockUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUseCase) EXPECT() *MockUseCaseMockRecorder {
	return m.recorder
}

// InitCategories mocks base method
func (m *MockUseCase) InitCategories(arg0 *[]models.Categories) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitCategories", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InitCategories indicates an expected call of InitCategories
func (mr *MockUseCaseMockRecorder) InitCategories(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitCategories", reflect.TypeOf((*MockUseCase)(nil).InitCategories), arg0)
}

// InitPairs mocks base method
func (m *MockUseCase) InitPairs(arg0 *[]models.Pairs) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitPairs", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InitPairs indicates an expected call of InitPairs
func (mr *MockUseCaseMockRecorder) InitPairs(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitPairs", reflect.TypeOf((*MockUseCase)(nil).InitPairs), arg0)
}

// InitProducts mocks base method
func (m *MockUseCase) InitProducts(arg0 *[]models.Products) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitProducts", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InitProducts indicates an expected call of InitProducts
func (mr *MockUseCaseMockRecorder) InitProducts(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitProducts", reflect.TypeOf((*MockUseCase)(nil).InitProducts), arg0)
}
