-- CREATE DATABASE mb_api WITH OWNER = postgres;
-- CREATE ROLE mb_api WITH SUPERUSER PASSWORD 'mb_api' LOGIN CONNECTION LIMIT -1;

CREATE TABLE IF NOT EXISTS products (
    id SERIAL PRIMARY KEY,
    name VARCHAR(32) NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS categories (
    id SERIAL PRIMARY KEY,
    name VARCHAR(32) NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS productcategories (
    id SERIAL PRIMARY KEY,
    product_id INTEGER REFERENCES products (id),
    category_id INTEGER REFERENCES categories (id)
);

GRANT ALL PRIVILEGES ON DATABASE mb_api TO mb_api;
GRANT USAGE ON SCHEMA public TO mb_api;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO mb_api;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO mb_api;